apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: dev-env
spec:
  selector:
    matchLabels:
      type: redis-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  
  
