apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: dev-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: passw0rd
        - name: MYSQL_DATABASE
          value: product
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc
