apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: dev-env
  labels:
    type: mariadb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/pakawat/redis/data/mariadb
