apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: dev-env
spec:
  selector:
    matchLabels:
      type: mariadb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
