apiVersion: v1
kind: Pod
metadata:
  name: k6-pod
  namespace: dev-env
spec:
  containers:
  - name: k6
    image: loadimpact/k6
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /script
        name: k6-conf
    env:
      - name: "K6_OUT"
        value: "influxdb=http://influxdb-service:8086/k6"
    command:
      - "k6"
      - "run"
      - "/script/test.js"
  volumes:
    - name: k6-conf
      configMap:
        name: k6-configmap
        items:
          - key: test.js
            path: test.js
          - key: test_redis.js
            path: test_redis.js
  restartPolicy: Never
