apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  namespace: dev-env
spec:
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: apploadtest:dev
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
